### ISSUE TITLE
Make the start experience smoother

### ISSUE THREAD

**Issue by isidorn** [serenadeai/code#2]
After I download the serenade extension I get a popup 

![Screenshot 2019-10-15 at 17 37 25](https://user-images.githubusercontent.com/1926584/66846707-80ef7e00-ef72-11e9-9d31-5b67fd652e46.png)

Can you just put a button that downloads the app automatically, and does not first open the site?
Can you make it more clear that there is an independent app neaded (was not clear to me first)?
Also popups on startup are very annoying, not sure how but this should be improved.

**Comment by tmacwill** [comment]
thanks for reporting! this is great feedback—the latest release replaces that popup with a more informational webview, and the download link there will download the latest version of the app directly.
