### ISSUE TITLE
Serenade.app stopped detecting VScode plugin after the last update of the Serenade app

### ISSUE THREAD

**Issue by markdestouches** [serenadeai/code#27]
OS: Fedora 34 with Gnome 40
VScode version: 1.56.2
Serenade plugin version: 1.4.9
Serenade.app version: 1.6.2

The title says it. Serenade no longer recognizes the VScode plugin. It can still launch and focus the editor and insert text with the 'system' command. The chrome plugin seems to work just fine.

Video demonstration: https://user-images.githubusercontent.com/70449077/119811388-b5b60c00-beef-11eb-8e0a-ecc4edcb34f3.mov

**Comment by tmacwill** [comment]
thanks for the report! we just released 1.6.3 on Linux, which should fix this issue. let us know if not!
