### ISSUE TITLE
Listen button has werid focus border

### ISSUE THREAD

**Issue by isidorn** [serenadeai/code#3]
Focus on the Listen button, the focus is weirdly rendered due to the chevron

![Screenshot 2019-10-15 at 17 40 35](https://user-images.githubusercontent.com/1926584/66846985-f0fe0400-ef72-11e9-9fbe-d990f48a971a.png)

**Comment by tmacwill** [comment]
thanks for reporting! we just release a new version of Serenade with a different UI for that button, so this should no longer be an issue!
