### ISSUE TITLE
Feature request: command palette support

### ISSUE THREAD

**Issue by isidorn** [serenadeai/code#5]
Suppport for entering commands in the command palette via voice.
Not sure if all the vscode api is there but this would be great

**Comment by RobertLowe** [comment]
@tmacwill

This is pretty important for workflow, but it would be great if we could just vocalize command shortcuts automagically.

Consider the following:

A vscode `keybindings.json`: 
```
  [{
    "key": "cmd+p",
    "command": "vscodex.predict"
  }]
```

We could augment this to: 

```
  [{
    "key": "cmd+p",
    "command": "vscodex.predict",
    "voice": "predict"
  }]
```

So, any time I say "predict", the command is run, and I get my OpenAI prediction!

**Comment by RobertLowe** [comment]
Alright, I implemented this:



```
// setup:
// cd ~/.serenade/scripts
// npm install --save jsonc
// create `custom.js` with the contents below:
// add a "voice" property to any of your keybindings.json in vscode
```

make sure you configure cmd+t to quick Open in `keybindings.json`

```
  ...
  {
    "key": "cmd+t",
    "command": "workbench.action.quickOpen",
    "voice": "quick open"
  },
  ...
  ```

`custom.js`
```javascript
const command = "command";
const option = "option";
const shift = "shift";
const control = "control";
const alt = "alt";

let jsonc = require('jsonc');

let fs = require('fs');
let settings = fs.readFileSync(`${process.env.HOME}/Library/Application Support/Code/User/keybindings.json`).toString();
settings = jsonc.parse(settings);

const press = async (shortcut, api) => {
  const [key, modifiers] = shortcut;
  await api.pressKey(key, modifiers);
 };

settings.forEach(setting => {
  if(setting.voice){
    serenade.app("code").command(setting.voice, async (api, matches) => {
      await press(["t", [command]], api);
      await api.typeText(`> ${setting.command}`);
      setTimeout(async ()=>{
        await press(["enter", [command]], api);
      }, 2000);
    });
  }
});
```

**Comment by tmacwill** [comment]
this is awesome—thanks for posting! adding the `voice` key to the VS Code keybindings file is super cool.

since this issue has been opened, we've also added the `evaluateInPlugin` API method: https://serenade.ai/docs/api/#reference. I think you should be able to say:

```
api.evaluateInPlugin("vscodex.predict");
```

and that will execute the `vscodex.predict` command within VS Code, which should be a bit faster since you don't have to wait on the VS Code UI. let me know if that works for you, and happy to help debug + fix if not!

**Comment by RobertLowe** [comment]
Thanks @tmacwill ! One thing I might look into is arguments, ex "predict 100", where 100 is passed as an argument to the vscode command. Note sure, `api.evaluateInPlugin` handles that?

Updated version:

```javascript
// setup:
// cd ~/.serenade/scripts
// npm install --save jsonc
// create `custom.js` with the contents here:
// add a "voice" property to any of your keybindings.json in vscode
let jsonc = require('jsonc');
let fs = require('fs');
let settings = fs.readFileSync(`${process.env.HOME}/Library/Application Support/Code/User/keybindings.json`).toString();
settings = jsonc.parse(settings);


settings.forEach(setting => {
  if(setting.voice){
    serenade.app("code").command(setting.voice, async (api, matches) => {
      api.evaluateInPlugin(setting.command);
    });
  }
});
```

**Comment by tmacwill** [comment]
ah gotcha, good point. `evaluateInPlugin` uses the `vscode.commands.executeCommand` function from the VS Code API (https://code.visualstudio.com/api/references/vscode-api). it looks like that VS Code API function can take arguments as well, so I think we should be able to add corresponding support to the Serenade API.

**Comment by RobertLowe** [comment]
@tmacwill that would be really great, I'll post a repo with the update, once the API changes are out. I love it, gonna show this to some co-workers
