### ISSUE TITLE
Serenade.app not working on MacOS Catalina

### ISSUE THREAD

**Issue by isidorn** [serenadeai/code#7]
Could not get it to work.
Might it be that your App needs Mic access and that Catalina disables this by default?
I also might be doing something stupid.

Speaking of mic: I notice that you have a mic dropdown and there you have all audio input / output. Could you not just show the Microphones, not the output?

**Comment by tmacwill** [comment]
thanks for reporting! we just released a new version of the app that supports the new permissions model introduced in Catalina, so should work now!
