### ISSUE TITLE
Bug: Opening website to "install client" happens on a continuous loop

### ISSUE THREAD

**Issue by kylper** [serenadeai/code#8]
I have the MacOS (installed on 10.13.6) version of the Serenade client, and the VSCode extension version 1.2.0. I installed the client first, then the extension.

At first I was not able to get the extension to recognize the existence of the client even after being reinstalled.

Yesterday, I encountered a bug where upon opening VSCode, the notification and subsequent redirect to the Serenade download page ```showInstallMessage``` in ```app.ts``` would continuously occur. I would be sent to a new Chrome Browser tab, then when I try to go back to my VSCode client, it would happen again.

I think the steps to recreate are pretty much laid out above, but if you need any more information or if there are any extension logs I can provide, please give me more information on how to find them. Thanks.

**Comment by tmacwill** [comment]
thanks for reporting! we'll take a look ASAP.
